stages:
 - install
 - build
 - test

install:
 stage: install
 image: node
 script:
  - npm prune
  - npm run setup
 artifacts:
  paths:
   - node_modules
   - frontend/node_modules
   - backend/node_modules
  expire_in: 30 mins

build:
 stage: build
 image: node
 script:
  - echo "Building.."
  - npm run build
  - echo "Build successful"
 artifacts:
  paths:
   - build

test:
 stage: test
 image: node
 script:
  - echo "Testing.."
  - CI=true npm test
  - echo "Test successful"