stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Building.."
    - npm run setup
    - cd frontend
    - chmod +x node_modules/.bin/react-scripts
    - npm run-script build
    - echo "Build successful"
  artifacts:
    expire_in: 15 minutes
    paths:
      - build

test:
  stage: test
  image: node
  script:
    - echo "Testing.."
    - npm run setup
    - chmod +x frontend/node_modules/.bin/react-scripts
    - CI=true npm test
    - echo "Test successful"