stages:
 - install
 - build
 - test

install:
 stage: install
 image: node
 script:
  - npm run setup
  - npm prune
  - cd frontend
  - npm prune
  - cd ..
  - cd backend
  - npm prune
 cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
   - node_modules
   - frontend/node_modules
   - backend/node_modules

build:
 stage: build
 image: node
 script:
  - echo "Building.."
  - cd frontend
  - npm run-script build
  - echo "Build successful"
 artifacts:
  paths:
   - build

test:
 stage: test
 image: node
 script:
  - echo "Testing.."
  - CI=true npm test
  - echo "Test successful"