stages:
 - install
 - build
 - test

installRoot:
 stage: install
 image: node
 script:
  - npm prune
  - npm install
 artifacts:
  paths:
   - node_modules
 only:
  changes:
   - package.json

installFront:
 stage: install
 image: node
 script:
  - cd frontend
  - npm prune
  - npm install
 artifacts:
  paths:
   - frontend/node_modules
 only:
  changes:
   - frontend/package.json

installBack:
 stage: install
 image: node
 script:
  - cd backend
  - npm prune
  - npm install
 artifacts:
  paths:
   - backend/node_modules
 only:
  changes:
   - backend/package.json

build:
 stage: build
 image: node
 script:
  - echo "Building.."
  - npm run build
  - echo "Build successful"
 artifacts:
  paths:
   - build

test:
 stage: test
 image: node
 script:
  - echo "Testing.."
  - CI=true npm test
  - echo "Test successful"