stages:
 - install
 - build
 - test

cache:
 key: ${CI_COMMIT_REF_SLUG}
 paths:
  - node_modules
  - frontend/node_modules
  - backend/node_modules

install:
 stage: install
 image: node
 script:
  - npm prune
  - npm run setup
 only:
  changes:
   - package.json
   - frontend/package.json
   - backend/package.json

build:
 stage: build
 image: node
 script:
  - echo "Building.."
  - npm run build
  - echo "Build successful"
 artifacts:
  paths:
   - build

test:
 stage: test
 image: node
 script:
  - echo "Testing.."
  - CI=true npm test
  - echo "Test successful"